variables:
  JFROG_REPO: adeo-docker-adeo-davidson-dev.jfrog.io
  DOCKER_IMAGE_TUTOBDD: tutobdd-elc

stages:
  - build
  - test
  - push_tuto
  - deploy

build:
  stage: build
  image: node:alpine
  tags:
    - docker
  script: 
    - node --check tutoapi/app.js

test:
  stage: test
  script:
    - echo "${JFROG_USER}"
    - echo "${JFROG_REPO}"

push_tuto:
  stage: push_tuto
  script:
    - docker login -u ${JFROG_USER} -p ${JFROG_TOKEN} ${JFROG_REPO}
    - cd bdd && docker build -t ${DOCKER_IMAGE_TUTOBDD} .
    - docker tag tutobdd-elc ${DOCKER_IMAGE_TUTOBDD}
    - docker push ${JFROG_REPO}/${DOCKER_IMAGE_TUTOBDD}:lastest


deploy:
  stage: deploy
  script:
    - echo "test deploy" 

