variables:
  JFROG_REPO: adeo-docker-adeo-davidson-dev.jfrog.io

stages:
  - build
  - test
  - push_tuto
  - deploy

build:
  stage: build
  image: node:alpine
  tags:
    - docker
  script: 
    - node --check tutoapi/app.js

test:
  stage: test
  script:
    - echo "${JFROG_USER}"
    - echo "${JFROG_REPO}"

push_tuto:
  stage: push_tuto
  script:
    - docker push ${JFROG_REPO}/tutoapi-elc:lastest


deploy:
  stage: deploy
  script:
    - echo "test deploy" 

