stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:alpine
  tags:
    - docker
  script: 
    - node --check tutoapi/app.js

test:
  stage: test
  script:
    - echo "test test"

deploy:
  stage: deploy
  script:
    - echo "test deploy" 

