stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - node -- check app.js

test:
  stage: test 
  script:
    - echo "test test"
deploy:
  stage: deploy
  script:
    - echo "test deploy" 

